version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tworld
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      # NOTA CLAVE: Dentro de Docker, "localhost" no funciona para conectarse a otro contenedor. 
      # Debemos usar el nombre del servicio de la base de datos, que es "db".
      DATABASE_URL: "postgresql://root:root@db:5432/tworld?schema=public"
      # NEXTAUTH_SECRET="tu_secreto_aqui" # Recuerda pasar las demás variables de entorno necesarias
    depends_on:
      - db

volumes:
  postgres_data: